//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity_Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class PesoxPeso_modelContainer : DbContext
    {
        public PesoxPeso_modelContainer()
            : base("name=PesoxPeso_modelContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Catalogo_Entidad_Federativa> Catalogo_Entidad_Federativa { get; set; }
        public virtual DbSet<tb_Generales_Accesos> tb_Generales_Accesos { get; set; }
        public virtual DbSet<tb_Generales_Accesos_Usuarios> tb_Generales_Accesos_Usuarios { get; set; }
        public virtual DbSet<tb_Generales_Usuarios_Contraseñas> tb_Generales_Usuarios_Contraseñas { get; set; }
        public virtual DbSet<Catalogo_Sector_Rubros> Catalogo_Sector_Rubros { get; set; }
        public virtual DbSet<Catalogo_Municipios> Catalogo_Municipios { get; set; }
        public virtual DbSet<Catalogo_Personalidad_Juridica> Catalogo_Personalidad_Juridica { get; set; }
        public virtual DbSet<Catalogo_Organos_Supremos> Catalogo_Organos_Supremos { get; set; }
        public virtual DbSet<Documentos_Consulta> Documentos_Consulta { get; set; }
        public virtual DbSet<tb_Generales_Parametros> tb_Generales_Parametros { get; set; }
        public virtual DbSet<Catalogo_Instituciones> Catalogo_Instituciones { get; set; }
        public virtual DbSet<tb_Generales_Usuarios> tb_Generales_Usuarios { get; set; }
        public virtual DbSet<Observaciones_Verificacion> Observaciones_Verificacion { get; set; }
        public virtual DbSet<Archivos_Instituciones> Archivos_Instituciones { get; set; }
        public virtual DbSet<Archivos_Adjuntos> Archivos_Adjuntos { get; set; }
        public virtual DbSet<Estatus_Registros> Estatus_Registros { get; set; }
        public virtual DbSet<Observaciones_Administrador> Observaciones_Administrador { get; set; }
        public virtual DbSet<Registro_Usuarios> Registro_Usuarios { get; set; }
        public virtual DbSet<Formulario_Estandar> Formulario_Estandar { get; set; }
    
        public virtual ObjectResult<sp_Buscar_Instituciones_Result> sp_Buscar_Instituciones(string nombre_buscar_institucion)
        {
            var nombre_buscar_institucionParameter = nombre_buscar_institucion != null ?
                new ObjectParameter("nombre_buscar_institucion", nombre_buscar_institucion) :
                new ObjectParameter("nombre_buscar_institucion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_Buscar_Instituciones_Result>("sp_Buscar_Instituciones", nombre_buscar_institucionParameter);
        }
    
        public virtual int sp_eliminar_institucion(Nullable<int> id_institucion)
        {
            var id_institucionParameter = id_institucion.HasValue ?
                new ObjectParameter("id_institucion", id_institucion) :
                new ObjectParameter("id_institucion", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_eliminar_institucion", id_institucionParameter);
        }
    
        public virtual int spr_Generales_agrega_acceso_por_usuario(Nullable<int> id_General_Usuario, Nullable<int> id_General_Acceso)
        {
            var id_General_UsuarioParameter = id_General_Usuario.HasValue ?
                new ObjectParameter("id_General_Usuario", id_General_Usuario) :
                new ObjectParameter("id_General_Usuario", typeof(int));
    
            var id_General_AccesoParameter = id_General_Acceso.HasValue ?
                new ObjectParameter("id_General_Acceso", id_General_Acceso) :
                new ObjectParameter("id_General_Acceso", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spr_Generales_agrega_acceso_por_usuario", id_General_UsuarioParameter, id_General_AccesoParameter);
        }
    
        public virtual int spr_Generales_borra_accesos_por_usuario(Nullable<int> id_General_Usuario)
        {
            var id_General_UsuarioParameter = id_General_Usuario.HasValue ?
                new ObjectParameter("id_General_Usuario", id_General_Usuario) :
                new ObjectParameter("id_General_Usuario", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spr_Generales_borra_accesos_por_usuario", id_General_UsuarioParameter);
        }
    
        public virtual int spr_Generales_Cambia_Variable_Contraseña(Nullable<int> id_usuario)
        {
            var id_usuarioParameter = id_usuario.HasValue ?
                new ObjectParameter("id_usuario", id_usuario) :
                new ObjectParameter("id_usuario", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spr_Generales_Cambia_Variable_Contraseña", id_usuarioParameter);
        }
    
        public virtual ObjectResult<spr_Generales_lee_accesos_Result> spr_Generales_lee_accesos()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spr_Generales_lee_accesos_Result>("spr_Generales_lee_accesos");
        }
    
        public virtual ObjectResult<spr_Generales_lee_accesos_por_usuario_Result> spr_Generales_lee_accesos_por_usuario(Nullable<int> id_General_Usuario, Nullable<bool> ver_no_visualizar, string sistema)
        {
            var id_General_UsuarioParameter = id_General_Usuario.HasValue ?
                new ObjectParameter("id_General_Usuario", id_General_Usuario) :
                new ObjectParameter("id_General_Usuario", typeof(int));
    
            var ver_no_visualizarParameter = ver_no_visualizar.HasValue ?
                new ObjectParameter("ver_no_visualizar", ver_no_visualizar) :
                new ObjectParameter("ver_no_visualizar", typeof(bool));
    
            var sistemaParameter = sistema != null ?
                new ObjectParameter("sistema", sistema) :
                new ObjectParameter("sistema", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spr_Generales_lee_accesos_por_usuario_Result>("spr_Generales_lee_accesos_por_usuario", id_General_UsuarioParameter, ver_no_visualizarParameter, sistemaParameter);
        }
    
        public virtual ObjectResult<spr_Generales_lee_accesos_por_usuario_catalogo_Result> spr_Generales_lee_accesos_por_usuario_catalogo(Nullable<int> id_General_Usuario)
        {
            var id_General_UsuarioParameter = id_General_Usuario.HasValue ?
                new ObjectParameter("id_General_Usuario", id_General_Usuario) :
                new ObjectParameter("id_General_Usuario", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spr_Generales_lee_accesos_por_usuario_catalogo_Result>("spr_Generales_lee_accesos_por_usuario_catalogo", id_General_UsuarioParameter);
        }
    
        public virtual int spr_Generales_lee_correo_usuario(Nullable<int> id_usuario)
        {
            var id_usuarioParameter = id_usuario.HasValue ?
                new ObjectParameter("id_usuario", id_usuario) :
                new ObjectParameter("id_usuario", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spr_Generales_lee_correo_usuario", id_usuarioParameter);
        }
    
        public virtual ObjectResult<string> spr_Generales_lee_funciones_usuario(Nullable<int> id_General_Usuario)
        {
            var id_General_UsuarioParameter = id_General_Usuario.HasValue ?
                new ObjectParameter("id_General_Usuario", id_General_Usuario) :
                new ObjectParameter("id_General_Usuario", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("spr_Generales_lee_funciones_usuario", id_General_UsuarioParameter);
        }
    
        public virtual ObjectResult<spr_Generales_lee_usuarios_por_estatus_Result> spr_Generales_lee_usuarios_por_estatus(Nullable<int> estatus)
        {
            var estatusParameter = estatus.HasValue ?
                new ObjectParameter("estatus", estatus) :
                new ObjectParameter("estatus", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spr_Generales_lee_usuarios_por_estatus_Result>("spr_Generales_lee_usuarios_por_estatus", estatusParameter);
        }
    
        public virtual int spr_Realiza_Cambio_Contraseña(Nullable<int> id_registro, string password)
        {
            var id_registroParameter = id_registro.HasValue ?
                new ObjectParameter("id_registro", id_registro) :
                new ObjectParameter("id_registro", typeof(int));
    
            var passwordParameter = password != null ?
                new ObjectParameter("password", password) :
                new ObjectParameter("password", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spr_Realiza_Cambio_Contraseña", id_registroParameter, passwordParameter);
        }
    
        public virtual int spr_Realiza_Cambio_GUID(Nullable<int> id_general_usuario, string guid)
        {
            var id_general_usuarioParameter = id_general_usuario.HasValue ?
                new ObjectParameter("id_general_usuario", id_general_usuario) :
                new ObjectParameter("id_general_usuario", typeof(int));
    
            var guidParameter = guid != null ?
                new ObjectParameter("guid", guid) :
                new ObjectParameter("guid", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spr_Realiza_Cambio_GUID", id_general_usuarioParameter, guidParameter);
        }
    
        public virtual ObjectResult<spr_Valida_Acceso_Sistema_Result> spr_Valida_Acceso_Sistema(string nombre_usuario, string password)
        {
            var nombre_usuarioParameter = nombre_usuario != null ?
                new ObjectParameter("nombre_usuario", nombre_usuario) :
                new ObjectParameter("nombre_usuario", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("password", password) :
                new ObjectParameter("password", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spr_Valida_Acceso_Sistema_Result>("spr_Valida_Acceso_Sistema", nombre_usuarioParameter, passwordParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> spr_Valida_Correo(string correo)
        {
            var correoParameter = correo != null ?
                new ObjectParameter("correo", correo) :
                new ObjectParameter("correo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("spr_Valida_Correo", correoParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> spr_Valida_eliminar_usuario(Nullable<int> id_General_Usuario)
        {
            var id_General_UsuarioParameter = id_General_Usuario.HasValue ?
                new ObjectParameter("id_General_Usuario", id_General_Usuario) :
                new ObjectParameter("id_General_Usuario", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("spr_Valida_eliminar_usuario", id_General_UsuarioParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> spr_Valida_GUID_Cambio_Contraseña(Nullable<int> id_general_usuario, string guid)
        {
            var id_general_usuarioParameter = id_general_usuario.HasValue ?
                new ObjectParameter("id_general_usuario", id_general_usuario) :
                new ObjectParameter("id_general_usuario", typeof(int));
    
            var guidParameter = guid != null ?
                new ObjectParameter("guid", guid) :
                new ObjectParameter("guid", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("spr_Valida_GUID_Cambio_Contraseña", id_general_usuarioParameter, guidParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> spr_Valida_Nombre_Correo_Usuario(string nombre_usuario, Nullable<int> id_general_usuario, string correo_usuario)
        {
            var nombre_usuarioParameter = nombre_usuario != null ?
                new ObjectParameter("nombre_usuario", nombre_usuario) :
                new ObjectParameter("nombre_usuario", typeof(string));
    
            var id_general_usuarioParameter = id_general_usuario.HasValue ?
                new ObjectParameter("id_general_usuario", id_general_usuario) :
                new ObjectParameter("id_general_usuario", typeof(int));
    
            var correo_usuarioParameter = correo_usuario != null ?
                new ObjectParameter("correo_usuario", correo_usuario) :
                new ObjectParameter("correo_usuario", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("spr_Valida_Nombre_Correo_Usuario", nombre_usuarioParameter, id_general_usuarioParameter, correo_usuarioParameter);
        }
    
        public virtual ObjectResult<sp_Buscar_registro_Result> sp_Buscar_registro(string nombre_buscar_institucion)
        {
            var nombre_buscar_institucionParameter = nombre_buscar_institucion != null ?
                new ObjectParameter("nombre_buscar_institucion", nombre_buscar_institucion) :
                new ObjectParameter("nombre_buscar_institucion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_Buscar_registro_Result>("sp_Buscar_registro", nombre_buscar_institucionParameter);
        }
    
        public virtual int sp_Registro_Usuario(string nombre_institucion, string responsable, string telefono, string correo, string rfc, string sucursal)
        {
            var nombre_institucionParameter = nombre_institucion != null ?
                new ObjectParameter("nombre_institucion", nombre_institucion) :
                new ObjectParameter("nombre_institucion", typeof(string));
    
            var responsableParameter = responsable != null ?
                new ObjectParameter("responsable", responsable) :
                new ObjectParameter("responsable", typeof(string));
    
            var telefonoParameter = telefono != null ?
                new ObjectParameter("telefono", telefono) :
                new ObjectParameter("telefono", typeof(string));
    
            var correoParameter = correo != null ?
                new ObjectParameter("correo", correo) :
                new ObjectParameter("correo", typeof(string));
    
            var rfcParameter = rfc != null ?
                new ObjectParameter("rfc", rfc) :
                new ObjectParameter("rfc", typeof(string));
    
            var sucursalParameter = sucursal != null ?
                new ObjectParameter("sucursal", sucursal) :
                new ObjectParameter("sucursal", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_Registro_Usuario", nombre_institucionParameter, responsableParameter, telefonoParameter, correoParameter, rfcParameter, sucursalParameter);
        }
    
        public virtual int sp_eliminar_personalidad(Nullable<int> id_personalidad)
        {
            var id_personalidadParameter = id_personalidad.HasValue ?
                new ObjectParameter("id_personalidad", id_personalidad) :
                new ObjectParameter("id_personalidad", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_eliminar_personalidad", id_personalidadParameter);
        }
    
        public virtual int sp_elimina_municipio(Nullable<int> id_municipio)
        {
            var id_municipioParameter = id_municipio.HasValue ?
                new ObjectParameter("id_municipio", id_municipio) :
                new ObjectParameter("id_municipio", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_elimina_municipio", id_municipioParameter);
        }
    
        public virtual int sp_eliminar_organo(Nullable<int> id_organo)
        {
            var id_organoParameter = id_organo.HasValue ?
                new ObjectParameter("id_organo", id_organo) :
                new ObjectParameter("id_organo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_eliminar_organo", id_organoParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> sp_contar_asignados()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("sp_contar_asignados");
        }
    
        public virtual ObjectResult<sp_contar_asignados1_Result> sp_contar_asignados1()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_contar_asignados1_Result>("sp_contar_asignados1");
        }
    }
}
