//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Archivos_Adjuntos
    {
        public int id_archivo_adjunto { get; set; }
        public int id_registro_solicitud { get; set; }
        public int numero_requisito { get; set; }
        public string descripcion_archivo { get; set; }
        public string url_archivo { get; set; }
    }
}
namespace Entity_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Archivos_Instituciones
    {
        public int id_documentacion { get; set; }
        public Nullable<int> id_institucion { get; set; }
        public byte[] acta_constitutiva { get; set; }
        public byte[] registro_federal_contribuyente { get; set; }
    }
}
namespace Entity_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Catalogo_Entidad_Federativa
    {
        public int id_entidad_federativa { get; set; }
        public string nombre_entidad { get; set; }
    }
}
namespace Entity_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Catalogo_Instituciones
    {
        public int id_institucion { get; set; }
        public string nombre_institucion { get; set; }
        public string nombre_director { get; set; }
        public string direccion { get; set; }
        public string telefono { get; set; }
        public int id_ciudad { get; set; }
        public string rfc { get; set; }
        public string sucursal { get; set; }
    }
}
namespace Entity_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Detalle_Poblacion_Atendida
    {
        public int id_formulario { get; set; }
        public int id_poblacion_atendida { get; set; }
        public string cantidad_hombres { get; set; }
        public string cantidad_mujeres { get; set; }
    }
}
namespace Entity_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Detalles_Oficinas_Operativas
    {
        public int id_oficina_operativa { get; set; }
        public int id_formulario { get; set; }
        public string calle_oficina_operativa { get; set; }
        public string numero_oficina_operativa { get; set; }
        public string colonia_oficina_operativa { get; set; }
        public string cp_oficina_operativa { get; set; }
        public string entre_calles_oficina_operativa { get; set; }
        public int id_municipio_oficinas_operativas { get; set; }
        public string telelefono_oficinas_operativas { get; set; }
        public string horarios { get; set; }
    }
}
namespace Entity_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Estatus_Registros
    {
        public int id_estatus_registro { get; set; }
        public Nullable<int> id_institucion { get; set; }
        public Nullable<int> id_registro { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public Nullable<int> estatus { get; set; }
    }
}
namespace Entity_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Formulario_Estandar
    {
        public int id_formulario_estandar { get; set; }
        public int id_institucion { get; set; }
        public int año_registro { get; set; }
        public int num_folio { get; set; }
        public System.DateTime fecha_recepcion { get; set; }
        public string nombre_dominio { get; set; }
        public string nombre_programa { get; set; }
        public string objetivo_social_programa { get; set; }
        public System.DateTime fecha_constitucion { get; set; }
        public int num_personas_laborando { get; set; }
        public int remunerados { get; set; }
        public int voluntarios { get; set; }
        public string areas_atencion { get; set; }
        public string areas_apoyo { get; set; }
        public int año_actual { get; set; }
        public int año_anterior { get; set; }
        public double total_ingresos { get; set; }
        public double total_donativos { get; set; }
        public double total_egresos { get; set; }
        public double monto_solicitado { get; set; }
        public string denominacion { get; set; }
        public string siglas { get; set; }
        public string telefono { get; set; }
        public string correo_electronico { get; set; }
        public string pagina_web { get; set; }
        public string red_social_institucion { get; set; }
        public string calle_numero { get; set; }
        public int id_municipio { get; set; }
        public string colonia { get; set; }
        public string CP { get; set; }
        public string celular { get; set; }
        public string telefonos { get; set; }
        public string correo_dom_fiscal { get; set; }
        public int id_personalidad_juridica { get; set; }
        public string otro_personalidad_juridica { get; set; }
        public string num_escritura { get; set; }
        public string volumen_num_escritura { get; set; }
        public System.DateTime fecha_escritura { get; set; }
        public string nombre_notario_publico { get; set; }
        public string numero_notario_publico { get; set; }
        public string lugar_notario_publico { get; set; }
        public string registro_propiedad { get; set; }
        public string volumen_registro_propiedad { get; set; }
        public System.DateTime fecha_registro_propiedad { get; set; }
        public int permiso_expedir_recibos { get; set; }
        public System.DateTime fecha_permiso { get; set; }
        public System.DateTime fecha_ultima_publicacion { get; set; }
        public string seccion { get; set; }
        public string pagina { get; set; }
        public int id_organo_supremo { get; set; }
        public string otro_organo_supremo { get; set; }
        public string nombre_representante_legal { get; set; }
        public string calle_representante_legal { get; set; }
        public string numero_representante_legal { get; set; }
        public string colonia_representante_legal { get; set; }
        public int id_ciudad_representante_legal { get; set; }
        public string telefono_representante_legal { get; set; }
        public string celular_representante_legal { get; set; }
        public string correo_representante { get; set; }
        public string rfc_representante { get; set; }
        public string descripcion_programa { get; set; }
        public string meta_programa { get; set; }
        public string diagnostico_situacional { get; set; }
        public string nombre_enlace { get; set; }
        public string telefono_enlace { get; set; }
        public string correo_enlace { get; set; }
        public string justificacion_programa { get; set; }
        public int poblacion_minima { get; set; }
        public int poblacion_maxima { get; set; }
        public int poblacion_actual { get; set; }
        public int tipo_ingreso_poblacion { get; set; }
        public int nivel_ingreso_poblacion { get; set; }
        public int rezago_educativo { get; set; }
        public double porcentaje_poblacion_atendida { get; set; }
        public int personas_hasta_15 { get; set; }
        public int personas_hasta_1982 { get; set; }
        public int personas_apartir_1982 { get; set; }
        public string piso { get; set; }
        public string piso_otro { get; set; }
        public string techo { get; set; }
        public string techo_otro { get; set; }
        public string muros { get; set; }
        public string muro_otro { get; set; }
        public int promedio_personas_viviendo { get; set; }
        public int num_habitaciones { get; set; }
        public string observaciones_acceso { get; set; }
        public int patrimonio_institucion { get; set; }
        public int propiedades_inmuebles { get; set; }
        public double valor_aproximado_inmuebles { get; set; }
        public int inversiones { get; set; }
        public double valor_aproximado_inversiones { get; set; }
        public int fideicomisos { get; set; }
        public double valor_aproximado_fideicomisos { get; set; }
        public double total_principales_fuentes { get; set; }
        public double total_principales_egresos { get; set; }
        public int impuesto_federal { get; set; }
        public int adeudos_fiscales { get; set; }
    }
}
namespace Entity_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Observaciones_Verificacion
    {
        public int id_observaciones_verificacion { get; set; }
        public int id_formulario { get; set; }
        public System.DateTime fecha_obsevaciones { get; set; }
        public string observaciones { get; set; }
        public int id_verificador { get; set; }
        public bool estatus { get; set; }
        public string tipo_persona { get; set; }
    }
}
namespace Entity_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Registro_Usuarios
    {
        public int id_registro { get; set; }
        public int id_formulario_estandar { get; set; }
        public string nombre_institucion { get; set; }
        public string rfc_institucion { get; set; }
        public string responsable { get; set; }
        public string telefono { get; set; }
        public string contraseña { get; set; }
        public string correo { get; set; }
        public System.DateTime fecha_registro { get; set; }
        public int id_institucion { get; set; }
        public string GUID { get; set; }
        public int id_verificador { get; set; }
        public int estatu_actual_registro { get; set; }
        public System.DateTime fecha_asignada { get; set; }
        public System.DateTime fecha_verificada { get; set; }
        public System.DateTime fecha_autorizada { get; set; }
        public string sucursal { get; set; }
    }
}
namespace Entity_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Generales_Accesos
    {
        public int id_General_Acceso { get; set; }
        public string funcion { get; set; }
        public string orden { get; set; }
        public string nombre_acceso { get; set; }
        public string imagen_acceso { get; set; }
        public string url { get; set; }
        public string nombre_sistema { get; set; }
    }
}
namespace Entity_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Generales_Accesos_Usuarios
    {
        public int id_General_Acceso_Usuario { get; set; }
        public int id_General_Usuario { get; set; }
        public int id_General_Acceso { get; set; }
    }
}
namespace Entity_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Generales_Parametros
    {
        public int año_registro { get; set; }
        public string correo_servidorSMTP { get; set; }
        public string correo_emailUsuario { get; set; }
        public string correo_emailPassword { get; set; }
        public string correo_correoReminente { get; set; }
        public string correo_nombreMostrar { get; set; }
        public int correo_puerto { get; set; }
        public bool correo_ssl { get; set; }
    }
}
namespace Entity_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Generales_Usuarios
    {
        public int id_General_Usuario { get; set; }
        public string nombre { get; set; }
        public int estatus { get; set; }
        public string correo { get; set; }
    }
}
namespace Entity_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Generales_Usuarios_Contraseñas
    {
        public int id_General_Usuario_Contraseña { get; set; }
        public int id_General_Usuario { get; set; }
        public string password { get; set; }
        public string GUID { get; set; }
    }
}
namespace Entity_Model
{
    using System;
    
    public partial class sp_Buscar_Instituciones_Result
    {
        public int id_institucion { get; set; }
        public string nombre_institucion { get; set; }
    }
}
namespace Entity_Model
{
    using System;
    
    public partial class sp_Valida_Acceso_Sistema_Usuario_Institucion_Result
    {
        public int id_registro { get; set; }
        public string responsable { get; set; }
    }
}
namespace Entity_Model
{
    using System;
    
    public partial class spr_Generales_lee_accesos_por_usuario_catalogo_Result
    {
        public int id_General_Acceso { get; set; }
        public string orden { get; set; }
        public string nombre_acceso { get; set; }
        public string url { get; set; }
    }
}
namespace Entity_Model
{
    using System;
    
    public partial class spr_Generales_lee_accesos_por_usuario_Result
    {
        public int id_General_Acceso { get; set; }
        public string orden { get; set; }
        public string nombre_acceso { get; set; }
        public string url { get; set; }
    }
}
namespace Entity_Model
{
    using System;
    
    public partial class spr_Generales_lee_accesos_Result
    {
        public int id_General_Acceso { get; set; }
        public string orden { get; set; }
        public string nombre_acceso { get; set; }
    }
}
namespace Entity_Model
{
    using System;
    
    public partial class spr_Generales_lee_funciones_instituciones_Result
    {
        public int id_General_Acceso { get; set; }
        public string orden { get; set; }
        public string nombre_acceso { get; set; }
        public string funcion { get; set; }
        public string url { get; set; }
    }
}
namespace Entity_Model
{
    using System;
    
    public partial class spr_Generales_lee_usuarios_por_estatus_Result
    {
        public int id_General_Usuario { get; set; }
        public string nombre { get; set; }
    }
}
namespace Entity_Model
{
    using System;
    
    public partial class spr_Sumar_Hombres_Mujeres_Result
    {
        public Nullable<int> Hombres { get; set; }
        public Nullable<int> Mujeres { get; set; }
    }
}
namespace Entity_Model
{
    using System;
    
    public partial class spr_Valida_Acceso_Sistema_Result
    {
        public int id_General_Usuario { get; set; }
        public string nombre { get; set; }
    }
}
